import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/organisms/Header/Header";
import TodoProvider from "@/contexts/TodoProvider";

export const metadata: Metadata = {
  title: "Todo List Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TodoProvider>
          <Header />
          <main className="main">{children}</main>
        </TodoProvider>
      </body>
    </html>
  );
}
